
const locations={
park:{title:"Park Plaza",facts:["Opened 1927 as Statler Hotel Boston","George B. Post & Sons","Renamed Park Plaza in 1998","One of New England's largest hotels","Back Bay fill occurred 1857-1882","450 acres created","Needham Heights gravel arrived by rail","Back Bay transformed marsh into planned neighborhood","Park Square was a transportation hub"]},
garden:{title:"Public Garden",facts:["Established 1837","America's first public botanical garden","Separate from Boston Common","Swan Boats operating since 1877","Operated by Paget family descendants","Make Way for Ducklings published 1941","Duck statues installed 1987","Sculpted by Nancy Schon","Ether Monument dedicated 1868","Commemorates 1846 anesthesia demonstration","Footbridge is iconic photo location"]},
arlington:{title:"Arlington Street Church",facts:["Completed 1861","Arthur Gilman architect","First major public building on filled Back Bay land","Inspired by St Martin-in-the-Fields London","Contains Tiffany windows","Long social justice history","Bells rang for first Boston Pride march in 1971"]},
mit:{title:"MIT on Boylston",facts:["MIT founded 1861","Known as Boston Tech","Original campus in Back Bay","Rogers Building stood near Boylston","Moved to Cambridge in 1916","William Barton Rogers founder","Plaque marks original area"]},
copley:{title:"Copley Square",facts:["Old South congregation founded 1669","Old South building completed 1875","Charles Amos Cummings architect","Willard Sears architect","Venetian Gothic style","Members included Benjamin Franklin","Members included Samuel Adams","Members included Phillis Wheatley","Trinity Church completed 1877","Henry Hobson Richardson architect","Richardsonian Romanesque style","Trinity replaced church lost after Great Boston Fire","Architects voted Trinity America's most important building in 1885","Hancock Tower completed 1976","Henry Cobb architect","Tallest building in New England","Glass panels failed after construction","Nickname world's tallest plywood building","Boston Public Library opened 1895","Three centuries of Boston history visible from one square"]},
library:{title:"Boston Public Library",facts:["Opened 1895","Charles Follen McKim architect","Beaux-Arts architecture","First large free municipal library in the United States","Inscription Free to All","Called a palace for the people","Inspired by Renaissance palaces","Bates Hall is one of Boston's great interiors","Contains major art collections","Public access to knowledge was core mission"]},
prudential:{title:"Prudential Center",facts:["Completed 1964","Built over Boston and Albany rail yards","Developed by Prudential Insurance","Tallest building in Boston when completed","Redefined skyline","Major urban renewal era project","Observation deck overlooks city","Initially controversial","Now a defining landmark"]}
};
function render(id){let s=locations[id];content.innerHTML=`<h2>${s.title}</h2><h3>Facts</h3><ul>${s.facts.map(f=>`<li>${f}</li>`).join('')}</ul>`}
function showLocation(id){render(id)}
function searchFacts(){let q=search.value.toLowerCase(); if(!q){showLocation('park');return;} let out='<h2>Search Results</h2>'; for(let k in locations){let hits=locations[k].facts.filter(f=>f.toLowerCase().includes(q)); if(hits.length){out+=`<h3>${locations[k].title}</h3><ul>${hits.map(h=>`<li>${h}</li>`).join('')}</ul>`}} content.innerHTML=out||'<h2>No results</h2>'}
function walkingFacts(){content.innerHTML='<h2>Walking Facts</h2><ul><li>Back Bay filled 1857-1882</li><li>Swan Boats since 1877</li><li>MIT began in Boston</li><li>Duck statues installed 1987</li><li>Ether Monument celebrates anesthesia</li></ul>'}
function saveMe(){content.innerHTML='<h2>Save Me</h2><ul><li>Back Bay: 1857-1882, 450 acres, Needham gravel</li><li>MIT: 1861, Boston Tech, 1916 move</li><li>Copley dates: 1669, 1875, 1877, 1895, 1976</li><li>Library: Free to All</li><li>Hancock: falling glass</li></ul>'}
showLocation('park');
