const pages={
park:{title:'Park Plaza',cards:[{title:'FACTS',items:['Opened 1927 as Statler Hotel Boston','George B. Post & Sons','Back Bay filled 1857-1882','450 acres created','Needham gravel arrived by rail']}]} ,
garden:{title:'Public Garden',cards:[{title:'LOOK AT',items:['Lagoon','Footbridge','Swan Boats','Ducklings','Ether Monument']},{title:'PUBLIC GARDEN',items:['Established 1837','America\'s first public botanical garden','Separate from Boston Common']},{title:'SWAN BOATS',items:['Operating since 1877','Created by Robert Paget','Still family operated']},{title:'MAKE WAY FOR DUCKLINGS',items:['Book published 1941','written/illustrated by Robert McCloskey','Nancy Schön sculptor','Installed 1987']},{title:'ETHER MONUMENT',items:['Dedicated 1868','Commemorates 1846 anesthesia demonstration','Does not mention ether by name']}]},
arlington:{title:'Arlington Street Church',cards:[{title:'FACTS',items:['Completed 1861','Arthur Gilman','First major public building on filled Back Bay land','Tiffany windows','Pride bells 1971']}]},
mit:{title:'MIT on Boylston Street',cards:[{title:'LOOK AT',items:['Boylston','Berkeley','Clarendon']},{title:'LOCATION',items:['Campus occupied block between Berkeley and Clarendon','Rogers Building near 497 Boylston']},{title:'MIT FACTS',items:['Founded 1861','William Barton Rogers','Boston Tech','Moved to Cambridge 1916','Plaque marks site']}]},
copley:{title:'Copley Square',cards:[{title:'OLD SOUTH CHURCH',items:['Founded 1669','Current building 1875','Charles Amos Cummings','Willard T. Sears','Venetian Gothic','Benjamin Franklin','Samuel Adams','Phillis Wheatley']},{title:'TRINITY CHURCH',items:['Completed 1877','Henry Hobson Richardson','Richardsonian Romanesque','Great Boston Fire connection','America\'s most important building (1885)']},{title:'HANCOCK TOWER',items:['Completed 1976','Henry Cobb','Tallest building in New England','Falling glass panels','World\'s Tallest Plywood Building nickname']},{title:'BOSTON PUBLIC LIBRARY',items:['Opened 1895','Charles Follen McKim','Beaux-Arts','Free to All']}]},
library:{title:'Boston Public Library',cards:[{title:'FACTS',items:['Opened 1895','Charles Follen McKim','Beaux-Arts architecture','First large free municipal library in the U.S.','Free to All']}]},
prudential:{title:'Prudential Center',cards:[{title:'FACTS',items:['Completed 1964','Built over rail yards','Developed by Prudential Insurance','Tallest building in Boston when completed','Redefined skyline']}]},
innovation:{title:'Innovation',cards:[{title:'INNOVATION',items:['MIT founded 1861','William Barton Rogers','1846 anesthesia demonstration','Back Bay engineering project: 450 acres','First large free municipal library in U.S.','Hancock engineering and glass replacement']} ]},
architects:{title:'Architects',cards:[{title:'ARCHITECTS',items:['George B. Post & Sons — Park Plaza','Arthur Gilman — Arlington Street Church','Henry Hobson Richardson — Trinity Church','Charles Amos Cummings — Old South','Willard T. Sears — Old South','Charles Follen McKim — Library','Henry Cobb — Hancock Tower']}]},
timeline:{title:'Timeline',cards:[{title:'DATES',items:['1630 Boston founded','1669 Old South congregation','1837 Public Garden','1846 Anesthesia demonstration','1861 MIT founded','1861 Arlington completed','1875 Old South completed','1877 Trinity completed','1895 Library opens','1916 MIT moves','1927 Statler Hotel opens','1964 Prudential','1976 Hancock']}]}
};
function renderPage(p){let h='<h2>'+p.title+'</h2>';p.cards.forEach(c=>{h+=`<div class="card"><h3>${c.title}</h3><ul>${c.items.map(i=>`<li>${i}</li>`).join('')}</ul></div>`});content.innerHTML=h;}
function showPage(id){renderPage(pages[id]);}
function searchCards(){const q=search.value.toLowerCase();if(!q){showPage('park');return;}let h='<h2>Search Results</h2>';for(const k in pages){let hits=[];pages[k].cards.forEach(c=>{if(c.title.toLowerCase().includes(q))hits.push(c.title);c.items.forEach(i=>{if(i.toLowerCase().includes(q))hits.push(i);});});if(hits.length){h+=`<div class="card"><h3>${pages[k].title}</h3><ul>${hits.map(x=>`<li>${x}</li>`).join('')}</ul></div>`}}content.innerHTML=h;}
showPage('park');
